class Equipment < ApplicationRecord
  belongs_to :user

  SPORTS = ["Category","Basketball", "Soccer", "Cricket", "Ballet", "Kayaking", "Rockclimbing",
"Fishing", "Archery",
"Badminton",
"Cricket",
"Bowling",
"Boxing",
"Curling",
"Tennis",
"Skateboarding",
"Surfing",
"Hockey",
"Figure skating",
"Yoga",
"Fencing",
"Fitness",
"Gymnastics",
"Karate",
"Volleyball",
"Weightlifting",
"Basketball",
"Baseball",
"Rugby",
"Wrestling",
"High jumping",
"Hang gliding",
"Car racing",
"Cycling",
"Running",
"Table tennis",
"Fishing",
"Judo",
"Climbing",
"Pool",
"Shooting",
"Horse racing",
"Horseback riding",
"Golf",
"Canoeing"]
end
